//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterWorldLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Busket
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> FishId { get; set; }
        public Nullable<int> InventoryId { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Fish Fish { get; set; }
        public virtual Inventory Inventory { get; set; }
        public virtual User User { get; set; }
    }
}
