//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterWorldLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInventory
    {
        public int Id { get; set; }
        public Nullable<int> InventoryId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> CountInventOrder { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Order Order { get; set; }
    }
}
